input:
  csv_path: slide_paths.csv

model:
  tile_level:
    foundation_model: "vit_large_patch14_dinov2.lvd142m"
    tile_size: 224
    batch_size: 64

tiling:
  spacing: 1.0
  tile_size: 224
  backend: "openslide"

speed:
  num_workers_preprocessing: 8
  num_workers_data_loading: 4

pooling:
  method: "tile-level-attention"

output:
  output_dir: "output"
